# Site settings
title: Tyler Field
email: thfield@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tyler's portfolio site on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thfield.github.io" # the base hostname & protocol for your site
twitter_username: thfield
github_username:  thfield

# Build settings
markdown: kramdown

images: "/images/"
